version: '3.5'

networks:
  database:
    name: mysql57_network
    driver: bridge
    internal: false
    
services:
  db:
    image: mysql:5.7
    container_name: mysql_57
    restart: always
    ports:
      - "${MYSQL_LOCAL_PORT}:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    labels:
      traefik.enbale: "false"
    networks:
      - database
